export default {
  // Invitations
  GET_INVITATIONS: 'GET_INVITATIONS',
  CREATE_INVITATION: 'CREATE_INVITATION',
  UPDATE_INVITATION: 'UPDATE_INVITATION',
  DELETE_INVITATION: 'DELETE_INVITATION',

  // Events
  GET_EVENTS: 'GET_EVENTS',
  CREATE_EVENT: 'CREATE_EVENT',
  UPDATE_EVENT: 'UPDATE_EVENT',
  DELETE_EVENT: 'DELETE_EVENT',

  // RSVPs
  GET_RSVPS: 'GET_RSVPS',
  CREATE_RSVP: 'CREATE_RSVP',
  UPDATE_RSVP: 'UPDATE_RSVP',
  DELETE_RSVP: 'DELETE_RSVP'
}
