export default {
  // Addresses
  GET_ADDRESSES: 'GET_ADDRESSES',
  CREATE_ADDRESS: 'CREATE_ADDRESS',
  UPDATE_ADDRESS: 'UPDATE_ADDRESS',
  DELETE_ADDRESS: 'DELETE_ADDRESS',

  // Events
  GET_EVENTS: 'GET_EVENTS',
  CREATE_EVENT: 'CREATE_EVENT',
  UPDATE_EVENT: 'UPDATE_EVENT',
  DELETE_EVENT: 'DELETE_EVENT',

  // Guests
  GET_GUESTS: 'GET_GUESTS',
  CREATE_GUEST: 'CREATE_GUEST',
  UPDATE_GUEST: 'UPDATE_GUEST',
  DELETE_GUEST: 'DELETE_GUEST',

  // Invitations
  GET_INVITATIONS: 'GET_INVITATIONS',
  CREATE_INVITATION: 'CREATE_INVITATION',
  UPDATE_INVITATION: 'UPDATE_INVITATION',
  DELETE_INVITATION: 'DELETE_INVITATION',

  // RSVPs
  GET_RSVPS: 'GET_RSVPS',
  CREATE_RSVP: 'CREATE_RSVP',
  UPDATE_RSVP: 'UPDATE_RSVP',
  DELETE_RSVP: 'DELETE_RSVP'
}
