export default {
  // Guests
  GET_GUESTS: 'GET_GUESTS',
  CREATE_GUEST: 'CREATE_GUEST',
  UPDATE_GUEST: 'UPDATE_GUEST',
  DELETE_GUEST: 'DELETE_GUEST',

  // Events
  GET_EVENTS: 'GET_EVENTS',
  CREATE_EVENT: 'CREATE_EVENT',
  UPDATE_EVENT: 'UPDATE_EVENT',
  DELETE_EVENT: 'DELETE_EVENT',

  // RSVPs
  GET_RSVPS: 'GET_RSVPS',
  CREATE_RSVP: 'CREATE_RSVP',
  UPDATE_RSVP: 'UPDATE_RSVP',
  DELETE_RSVP: 'DELETE_RSVP'
}
